### ISSUE TITLE
float64 Sqrt faster than float32 Sqrt?

### ISSUE THREAD

**Issue by rkusa** [rkusa/gm#1]
Someone any idea why this is so?

Tested on an i5 with 2.9GHz

```
BenchmarkSqrtFloat64-4  100000000           10.0 ns/op
BenchmarkSqrtFloat32-4  100000000           12.8 ns/op
```

``` asm
// func Sqrt(x float64) float64
TEXT ·Sqrt(SB),NOSPLIT,$0
    SQRTSD x+0(FP), X0
    MOVSD X0, ret+8(FP)
    RET
```

&

``` go
float32(Sqrt(float64(x)))
```

vs

``` asm
// func Sqrt(x float32) float32
TEXT ·Sqrt(SB),NOSPLIT,$0
    SQRTSS x+0(FP), X0
    MOVSS X0, ret+8(FP)
    RET
```

**Comment by quillaja** [comment]
I've just been dabbling in go asm and simd, but I've read that function implemented in asm cannot be inlined. Therefore when used in a loop, you suffer the penalty of a function call each iteration. Using plain go, the compiler can inline simple functions. My own non-rigorous testing has also shown this.

**Comment by rkusa** [comment]
Interesting, thanks for sharing @quillaja !
